Trying to build docker image with application source and push it to dockerhub (anaconda is present but not used)
- FIX: ADD requires at least two arguments    {Added destination to all ADD commands despite of WORKDIR command}
- FIX: ADD failed: stat /var/lib/docker/tmp/docker-builder534739647/LICENSE: no such file or directory {Removed LICENSE from .dockerignore}
- FIX: ADD failed: stat /var/lib/docker/tmp/docker-builder818427838/README.md: no such file or directory {Removed LICENSE from .dockerignore}
- FIX: /bin/sh: 1: where: not found {Removed use of where command and used python3 --version}
- FIX: Commented out twisted as not installing on normal python on travis ci
- FIX: Upgrade pip to latest as instructed on travis ci command line
- FIX: Instead of `python3 -m pip ...` using `pip` and re-enabled twisted as it is required by unknown dependencies also
- FIX: Unable to execute 'gcc': No such file or directory, error: command 'gcc' failed with exit status 1 {installing essential linux utilities including sudo}
- FIX: Twisted issue twisted>=18.7.0 {back to original version}
- FIX: /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory {installed essential linux libraries via apt-get}
- FIX: Modified execute command for python
- FIX: Added > /dev/null to long commands
- FTR: Split apt-get essentials to move apt-utils before
- FTR: - Using `--no-cache-dir  --upgrade --ignore-installed` for pip installs to shrink image,
choose upgrade and ignore existing installs in .travis.yml and Docker file
- FIX: # Change Execute Bit on Python Files  {RUN find ./**/*.py -type f -exec chmod 755 {} \;}
- FIX: Made apps as app at some places, this was a typo
- FIX: Convert CMD ["python3", "/app/main.py"] to execute form with change directory and print of pwd
- FIX: Commented install of DEV Packages on Travis (But they're installed in docker)
- FIX: Placed setuptools>=40.4.3 and wheel>= 0.31.1 so that package building by python will be proper.
Also setuptools and wheels required on system for proper installation of python packages
- FIX: Commenting `set -ev` in scripts/git-taglocally.sh as this could be causing Travis to continue
publish package even if build step fails. Some places says `set -ev` is dangerous
- FIX: Docker ADD command made 'ADD data/ /app/data/' so that directory structure is maintained
This will ensure app will execute properly
- FIX: Sphinx is a document generation tool in python, thus sphinx>=1.7.9 moved to requirements-dev.txt
This will ensure that .travis.yml using requirements-dev.txt can build docs
- Added script to build docker image